// ======================================================
// BREEDS.JS — Comprehensive dog breed database
// 110+ breeds: common, popular mixed breeds, rare & unusual
// ======================================================

const BREED_DATABASE = {

  // ── SPORTING ──────────────────────────────────────────
  'Labrador Retriever': {
    group: 'Sporting', size: 'large', activityLevel: 4,
    walkMinsPerDay: 60, idealWalksPerDay: 2,
    weightRangeKg: [25, 36], caloriesPerKgBase: 60,
    coat: 'Short, dense, water-resistant',
    temperament: 'Friendly, outgoing, active, trusting',
    traits: ['Great family dog', 'Very food motivated', 'Loves water', 'Easy to train'],
    healthNotes: 'Prone to hip dysplasia and obesity. Monitor weight closely.',
    feedingNotes: 'Highly food-motivated breed. Measure meals strictly to prevent obesity. Split into 2 meals per day.',
    originalPurpose: 'Retrieving game from water',
    fun: 'One of the most popular breeds worldwide for over 30 years!',
  },
  'Golden Retriever': {
    group: 'Sporting', size: 'large', activityLevel: 4,
    walkMinsPerDay: 60, idealWalksPerDay: 2,
    weightRangeKg: [25, 34], caloriesPerKgBase: 58,
    coat: 'Dense, water-repellent, straight or wavy',
    temperament: 'Friendly, reliable, trustworthy, kind',
    traits: ['Excellent with children', 'Loves to fetch', 'Very trainable', 'Affectionate'],
    healthNotes: 'Prone to hip dysplasia and certain cancers. Regular vet checks recommended.',
    feedingNotes: 'Feed high-quality protein diet. Adjust portions based on walk activity.',
    originalPurpose: 'Retrieving waterfowl during hunts',
    fun: 'Third most popular breed in the US. Famous for their "smile"!',
  },
  'Irish Setter': {
    group: 'Sporting', size: 'large', activityLevel: 5,
    walkMinsPerDay: 80, idealWalksPerDay: 2,
    weightRangeKg: [27, 32], caloriesPerKgBase: 62,
    coat: 'Long, silky, mahogany or chestnut red',
    temperament: 'Energetic, playful, exuberant, affectionate',
    traits: ['High energy', 'Needs space to run', 'Very friendly', 'Beautiful coat'],
    healthNotes: 'Can be restless if under-exercised. Prone to hip dysplasia.',
    feedingNotes: 'High-energy breed needs protein-rich diet. Extra calories on active days.',
    originalPurpose: 'Bird hunting',
    fun: 'Their gorgeous red coat is one of the most distinctive in the dog world.',
  },
  'Vizsla': {
    group: 'Sporting', size: 'medium', activityLevel: 5,
    walkMinsPerDay: 90, idealWalksPerDay: 2,
    weightRangeKg: [20, 29], caloriesPerKgBase: 65,
    coat: 'Short, smooth, golden-rust',
    temperament: 'Affectionate, energetic, gentle, loyal',
    traits: ['Velcro dog — loves to be with people', 'Very high energy', 'Athletic', 'Sensitive'],
    healthNotes: 'Generally healthy. Prone to hip dysplasia if over-exercised as a puppy.',
    feedingNotes: 'Lean and athletic — needs quality protein. Monitor for weight loss during heavy activity.',
    originalPurpose: 'Hunting pointer and retriever',
    fun: 'Known as "Velcro Vizslas" — they hate being left alone!',
  },
  'Weimaraner': {
    group: 'Sporting', size: 'large', activityLevel: 5,
    walkMinsPerDay: 90, idealWalksPerDay: 2,
    weightRangeKg: [25, 40], caloriesPerKgBase: 60,
    coat: 'Short, sleek, silver-grey',
    temperament: 'Friendly, fearless, alert, obedient',
    traits: ['Needs a lot of exercise', 'Intelligent', 'Headstrong', 'Devoted'],
    healthNotes: 'Risk of bloat (GDV). Never exercise immediately after eating.',
    feedingNotes: 'Feed 2-3 small meals to reduce bloat risk. Avoid exercise for 1hr after feeding.',
    originalPurpose: 'All-purpose gun dog',
    fun: 'Nicknamed the "Grey Ghost" for their striking silver coats.',
  },
  'Flat-Coated Retriever': {
    group: 'Sporting', size: 'large', activityLevel: 4,
    walkMinsPerDay: 60, idealWalksPerDay: 2,
    weightRangeKg: [25, 36], caloriesPerKgBase: 58,
    coat: 'Dense, flat-lying, black or liver',
    temperament: 'Optimistic, exuberant, cheerful, devoted',
    traits: ['Stays puppy-like well into adulthood', 'Loves water', 'Easy going'],
    healthNotes: 'Higher cancer risk than most breeds. Regular vet checks essential.',
    feedingNotes: 'Moderate feeder. High-quality protein supports their active lifestyle.',
    originalPurpose: 'Retrieving game on land and water',
    fun: 'Called the "Peter Pan" of dogs for their eternal puppy spirit!',
  },
  'German Shorthaired Pointer': {
    group: 'Sporting', size: 'large', activityLevel: 5,
    walkMinsPerDay: 90, idealWalksPerDay: 2,
    weightRangeKg: [20, 32], caloriesPerKgBase: 65,
    coat: 'Short, thick, liver and white',
    temperament: 'Intelligent, bold, boisterous, trainable',
    traits: ['Extremely athletic', 'Versatile working dog', 'Loves swimming', 'High energy'],
    healthNotes: 'Risk of hip dysplasia. Needs daily vigorous exercise to prevent behavioural issues.',
    feedingNotes: 'High-energy diet essential. Can require up to 1600 kcal/day when very active.',
    originalPurpose: 'All-purpose hunting dog',
    fun: 'Can point, retrieve, track and swim — a true all-rounder.',
  },
  'Gordon Setter': {
    group: 'Sporting', size: 'large', activityLevel: 4,
    walkMinsPerDay: 70, idealWalksPerDay: 2,
    weightRangeKg: [20, 32], caloriesPerKgBase: 58,
    coat: 'Long, silky, black and tan',
    temperament: 'Bold, confident, loyal, steady',
    traits: ['Devoted to family', 'Good-natured', 'Needs vigorous daily exercise'],
    healthNotes: 'Eye conditions and hip dysplasia risk.',
    feedingNotes: 'Feed a balanced diet. Adjust for activity level.',
    originalPurpose: 'Scottish bird hunting',
    fun: 'The heaviest of all setter breeds.',
  },

  // ── HERDING ───────────────────────────────────────────
  'Border Collie': {
    group: 'Herding', size: 'medium', activityLevel: 5,
    walkMinsPerDay: 90, idealWalksPerDay: 3,
    weightRangeKg: [14, 20], caloriesPerKgBase: 70,
    coat: 'Rough or smooth double coat, various colours',
    temperament: 'Energetic, intelligent, tenacious, responsive',
    traits: ['Considered the most intelligent dog breed', 'Needs mental stimulation', 'Herding instinct', 'Obsessive about tasks'],
    healthNotes: 'Prone to epilepsy and Collie Eye Anomaly. Mental exercise as important as physical.',
    feedingNotes: 'High-energy breed. Active dogs need 1400-1800 kcal/day. Feed quality protein.',
    originalPurpose: 'Herding livestock (sheep)',
    fun: 'Can learn the names of over 1,000 objects!',
  },
  'Australian Shepherd': {
    group: 'Herding', size: 'medium', activityLevel: 5,
    walkMinsPerDay: 90, idealWalksPerDay: 2,
    weightRangeKg: [16, 32], caloriesPerKgBase: 65,
    coat: 'Medium-length, wavy or straight double coat',
    temperament: 'Intelligent, work-oriented, exuberant, devoted',
    traits: ['Multi-coloured merle coats', 'Highly trainable', 'Needs jobs to do', 'Can be vocal'],
    healthNotes: 'MDR1 gene mutation common — always check medications with vet.',
    feedingNotes: 'Active lifestyle demands high-quality protein and fat. Adjust for workload.',
    originalPurpose: 'Herding livestock in the American West',
    fun: 'Despite the name, they were developed in the United States, not Australia!',
  },
  'German Shepherd': {
    group: 'Herding', size: 'large', activityLevel: 4,
    walkMinsPerDay: 60, idealWalksPerDay: 2,
    weightRangeKg: [22, 40], caloriesPerKgBase: 60,
    coat: 'Medium-length double coat, tan and black or sable',
    temperament: 'Courageous, confident, smart, loyal',
    traits: ['Versatile working dog', 'Protective', 'Easy to train', 'Loyal to family'],
    healthNotes: 'Hip and elbow dysplasia very common. Degenerative myelopathy in older dogs.',
    feedingNotes: 'Feed twice daily. Joint-supporting supplements (glucosamine) beneficial.',
    originalPurpose: 'Herding sheep, police and military work',
    fun: 'Second most popular dog breed globally. Used in search & rescue, police, military worldwide.',
  },
  'Shetland Sheepdog': {
    group: 'Herding', size: 'small', activityLevel: 4,
    walkMinsPerDay: 60, idealWalksPerDay: 2,
    weightRangeKg: [6, 11], caloriesPerKgBase: 75,
    coat: 'Long, rough outer coat with dense undercoat',
    temperament: 'Playful, energetic, intelligent, loyal',
    traits: ['Vocal — loves to bark', 'Great with children', 'Fast learner', 'Sensitive'],
    healthNotes: 'MDR1 gene mutation common. Eye conditions (Collie Eye Anomaly) possible.',
    feedingNotes: 'Small dog with high energy — feed proportionally. Quality kibble recommended.',
    originalPurpose: 'Herding sheep and ponies in Shetland Islands',
    fun: 'Despite looking like a mini Rough Collie, Shelties are a distinct breed.',
  },
  'Welsh Corgi (Pembroke)': {
    group: 'Herding', size: 'small', activityLevel: 4,
    walkMinsPerDay: 60, idealWalksPerDay: 2,
    weightRangeKg: [10, 14], caloriesPerKgBase: 72,
    coat: 'Medium-length, thick double coat',
    temperament: 'Smart, affectionate, alert, bold',
    traits: ['Low to the ground but big personality', 'Loves to herd', 'Vocal'],
    healthNotes: 'Long back makes them prone to intervertebral disc disease. Avoid excessive jumping.',
    feedingNotes: 'Monitor weight carefully — prone to obesity. Avoid overfeeding treats.',
    originalPurpose: 'Cattle herding',
    fun: 'Favourite breed of Queen Elizabeth II who owned over 30 Corgis!',
  },
  'Belgian Malinois': {
    group: 'Herding', size: 'large', activityLevel: 5,
    walkMinsPerDay: 90, idealWalksPerDay: 3,
    weightRangeKg: [22, 34], caloriesPerKgBase: 68,
    coat: 'Short, straight, fawn to mahogany with black mask',
    temperament: 'Confident, hardworking, intense, protective',
    traits: ['Favourite of police and military', 'Extremely driven', 'Needs experienced owner', 'High intensity'],
    healthNotes: 'Generally very hardy. Hip dysplasia possible. Boredom can cause destructive behaviour.',
    feedingNotes: 'Working dog energy needs. A very active Malinois may need 1800+ kcal/day.',
    originalPurpose: 'Herding, police, military, personal protection',
    fun: 'US Navy SEAL raid on Osama Bin Laden included a Belgian Malinois named Cairo.',
  },

  // ── WORKING ───────────────────────────────────────────
  'Siberian Husky': {
    group: 'Working', size: 'large', activityLevel: 5,
    walkMinsPerDay: 90, idealWalksPerDay: 2,
    weightRangeKg: [16, 27], caloriesPerKgBase: 65,
    coat: 'Thick double coat, various colours',
    temperament: 'Outgoing, mischievous, loyal, gentle',
    traits: ['Loves to run — never off-lead unless secured', 'Vocal (howls)', 'Escape artist', 'Pack-oriented'],
    healthNotes: 'Eye conditions (cataracts). Risk of hypothyroidism. Dense coat — heat intolerant.',
    feedingNotes: 'Surprisingly efficient metabolism. Some Huskies eat less than expected. Monitor weight.',
    originalPurpose: 'Sled pulling in Siberia',
    fun: 'A team of Siberian Huskies ran 340 miles to deliver diphtheria medicine to Nome, Alaska in 1925.',
  },
  'Alaskan Malamute': {
    group: 'Working', size: 'large', activityLevel: 4,
    walkMinsPerDay: 90, idealWalksPerDay: 2,
    weightRangeKg: [34, 45], caloriesPerKgBase: 55,
    coat: 'Thick, coarse double coat',
    temperament: 'Affectionate, loyal, playful, dignified',
    traits: ['Independent', 'Pack animal — needs company', 'Strong-willed', 'Not suitable for hot climates'],
    healthNotes: 'Hip dysplasia and chondrodysplasia. Never shave their double coat.',
    feedingNotes: 'Large, powerful breed. 2-3 cups high-quality dry food split into 2 meals.',
    originalPurpose: 'Heavy freight sledding',
    fun: 'One of the oldest and largest Arctic sled dogs.',
  },
  'Rottweiler': {
    group: 'Working', size: 'large', activityLevel: 3,
    walkMinsPerDay: 60, idealWalksPerDay: 2,
    weightRangeKg: [35, 60], caloriesPerKgBase: 52,
    coat: 'Short, dense, black with tan markings',
    temperament: 'Loyal, loving, confident guardian',
    traits: ['Natural guard dog', 'Devoted to family', 'Needs firm training from young age'],
    healthNotes: 'Hip and elbow dysplasia. Aortic stenosis heart condition. Keep at healthy weight.',
    feedingNotes: 'Large breed — feed slow feeders to prevent bloat. 2 meals per day.',
    originalPurpose: 'Herding livestock, pulling carts, guarding',
    fun: 'Roman armies used Rottweiler ancestors to herd cattle across Europe.',
  },
  'Doberman Pinscher': {
    group: 'Working', size: 'large', activityLevel: 5,
    walkMinsPerDay: 80, idealWalksPerDay: 2,
    weightRangeKg: [27, 45], caloriesPerKgBase: 62,
    coat: 'Short, sleek, blue/black/red/fawn with rust markings',
    temperament: 'Loyal, fearless, alert, intelligent',
    traits: ['Elite guard dog', 'Very trainable', 'Velcro dog with their person', 'Athletic'],
    healthNotes: 'Dilated cardiomyopathy (heart disease) — annual cardiac screening recommended.',
    feedingNotes: 'Athletic build — needs protein-rich food. Avoid feeding before exercise (bloat risk).',
    originalPurpose: 'Personal protection and guard dog',
    fun: 'Created in the 1890s by tax collector Louis Dobermann who wanted a loyal guard dog for his rounds.',
  },
  'Great Dane': {
    group: 'Working', size: 'giant', activityLevel: 3,
    walkMinsPerDay: 60, idealWalksPerDay: 2,
    weightRangeKg: [50, 82], caloriesPerKgBase: 45,
    coat: 'Short, thick, glossy',
    temperament: 'Friendly, patient, dependable, gentle',
    traits: ['Gentle giant', 'Great with people', 'Apartment-friendly despite size', 'Short-lived joy due to lifespan'],
    healthNotes: 'High risk of bloat (GDV) — avoid exercise after meals. Hip dysplasia. Short lifespan (7-10 years).',
    feedingNotes: 'Feed 3 small meals to reduce bloat risk. Never exercise within 2 hours of eating.',
    originalPurpose: 'Boar hunting, estate guarding',
    fun: 'Scooby-Doo is a Great Dane!',
  },
  'Saint Bernard': {
    group: 'Working', size: 'giant', activityLevel: 2,
    walkMinsPerDay: 45, idealWalksPerDay: 2,
    weightRangeKg: [64, 120], caloriesPerKgBase: 42,
    coat: 'Rough or smooth, orange, mahogany, red-brindle',
    temperament: 'Gentle, friendly, watchful, patient',
    traits: ['Gentle giant', 'Good with kids', 'Drools a lot', 'Low energy indoors'],
    healthNotes: 'Hip and elbow dysplasia. Heat intolerant. Bloat risk.',
    feedingNotes: 'Massive caloric needs despite modest energy. Feed high-protein, joint-supporting food.',
    originalPurpose: 'Alpine rescue in Swiss mountains',
    fun: 'Saint Bernards have rescued over 2,000 people in the Swiss Alps!',
  },
  'Newfoundland': {
    group: 'Working', size: 'giant', activityLevel: 3,
    walkMinsPerDay: 60, idealWalksPerDay: 2,
    weightRangeKg: [45, 70], caloriesPerKgBase: 44,
    coat: 'Flat, dense, water-resistant, black or brown',
    temperament: 'Sweet, patient, devoted, gentle',
    traits: ['Natural water rescue instinct', 'Great with children', 'Very calm indoors'],
    healthNotes: 'Sub-aortic stenosis (heart) and hip dysplasia. Regular cardiac checks advised.',
    feedingNotes: 'Large appetite — feed quality food, avoid overfeeding. 2 meals per day.',
    originalPurpose: 'Water rescue and working dog for fishermen',
    fun: 'Newfoundlands have webbed feet and a water-resistant coat making them natural swimmers.',
  },
  'Leonberger': {
    group: 'Working', size: 'giant', activityLevel: 3,
    walkMinsPerDay: 60, idealWalksPerDay: 2,
    weightRangeKg: [41, 75], caloriesPerKgBase: 46,
    coat: 'Long, lion-like, lush, golden to mahogany',
    temperament: 'Gentle, patient, playful, good-natured',
    traits: ['Majestic appearance', 'Excellent family dog', 'Loves water', 'Loyal'],
    healthNotes: 'Polyneuropathy (nerve disorder) fairly common. Hip dysplasia.',
    feedingNotes: 'High-quality large-breed food. Joint supplements from 2 years old recommended.',
    originalPurpose: 'Symbol of the Town of Leonberg, draft and farm dog',
    fun: 'Created to resemble the lion on the coat of arms of Leonberg, Germany.',
  },
  'Samoyed': {
    group: 'Working', size: 'large', activityLevel: 4,
    walkMinsPerDay: 60, idealWalksPerDay: 2,
    weightRangeKg: [16, 30], caloriesPerKgBase: 60,
    coat: 'Thick, fluffy, white or cream double coat',
    temperament: 'Friendly, gentle, adaptable, alert',
    traits: ['The Sammy smile', 'Loves everyone', 'Vocal', 'Cold weather dog'],
    healthNotes: 'Samoyed hereditary glomerulopathy (kidney disease). Hip dysplasia.',
    feedingNotes: 'Quality protein diet. Active breed — adjust portions for activity level.',
    originalPurpose: 'Reindeer herding, sled pulling, hunting',
    fun: 'Their upturned corners of the mouth (the "Sammy smile") prevent drooling in cold temperatures.',
  },
  'Akita': {
    group: 'Working', size: 'large', activityLevel: 3,
    walkMinsPerDay: 60, idealWalksPerDay: 2,
    weightRangeKg: [32, 59], caloriesPerKgBase: 55,
    coat: 'Double coat, short to medium length',
    temperament: 'Alert, dignified, profoundly loyal, reserved',
    traits: ['One-person or family dog', 'Independent thinker', 'Not good with other dogs', 'Quiet and dignified'],
    healthNotes: 'Auto-immune conditions. Hip dysplasia. Bloat risk.',
    feedingNotes: 'Feed 2 times per day. Limit exercise around meal times.',
    originalPurpose: 'Hunting bears and guarding Japanese royalty',
    fun: 'Hachiko the Akita waited at a train station every day for 10 years after his owner\'s death.',
  },
  'Chow Chow': {
    group: 'Working', size: 'large', activityLevel: 2,
    walkMinsPerDay: 45, idealWalksPerDay: 2,
    weightRangeKg: [20, 32], caloriesPerKgBase: 55,
    coat: 'Very dense, rough or smooth lion mane ruff',
    temperament: 'Aloof, loyal, quiet, independent',
    traits: ['Blue-black tongue', 'Very clean — cat-like', 'Loyal to owner', 'Not overly friendly to strangers'],
    healthNotes: 'Hip dysplasia and eye conditions. Heat-sensitive due to coat thickness.',
    feedingNotes: 'Moderate feeder. Can be picky. High-quality protein-based diet.',
    originalPurpose: 'Hunting, guarding, pulling sleds',
    fun: 'One of the oldest dog breeds in the world — DNA evidence shows links to ancient China.',
  },
  'Mastiff': {
    group: 'Working', size: 'giant', activityLevel: 2,
    walkMinsPerDay: 40, idealWalksPerDay: 2,
    weightRangeKg: [54, 100], caloriesPerKgBase: 40,
    coat: 'Short, apricot, fawn or brindle',
    temperament: 'Gentle, courageous, calm, dignified',
    traits: ['Gentle giant', 'Massive frame', 'Protective', 'Prefers loafing to running'],
    healthNotes: 'Hip and elbow dysplasia. Bloat risk. Short lifespan.',
    feedingNotes: 'Despite size, does not need huge quantities. Monitor weight. Avoid bloat — feed twice daily.',
    originalPurpose: 'Estate guardian, war dog',
    fun: 'The heaviest dog breed — record Mastiff weighed 343 lbs!',
  },
  'Great Pyrenees': {
    group: 'Working', size: 'large', activityLevel: 3,
    walkMinsPerDay: 60, idealWalksPerDay: 2,
    weightRangeKg: [39, 54], caloriesPerKgBase: 48,
    coat: 'Thick, weather-resistant, white or ivory',
    temperament: 'Calm, gentle, patient, smart',
    traits: ['Nocturnal tendencies — barks at night', 'Natural livestock guardian', 'Gentle with family'],
    healthNotes: 'Bone cancer and bloat risk. Hip dysplasia.',
    feedingNotes: 'Surprisingly not a big eater for their size. Quality food twice daily.',
    originalPurpose: 'Guarding flocks in the Pyrenees mountains',
    fun: 'Has double dewclaws on its back feet — nature\'s snowshoes!',
  },
  'Cane Corso': {
    group: 'Working', size: 'large', activityLevel: 4,
    walkMinsPerDay: 60, idealWalksPerDay: 2,
    weightRangeKg: [40, 50], caloriesPerKgBase: 56,
    coat: 'Short, coarse, black/grey/fawn/red',
    temperament: 'Intelligent, loyal, trainable, quiet',
    traits: ['Powerful protector', 'Needs firm but fair training', 'Not suitable for first-time owners'],
    healthNotes: 'Hip dysplasia and bloat risk. Eye and skin conditions.',
    feedingNotes: 'Feed quality large-breed food. 2 meals per day. Avoid exercise after meals.',
    originalPurpose: 'War dog, farm guarding, hunting large game',
    fun: 'Name comes from Latin "cohors" meaning guardian or protector.',
  },
  'Dogo Argentino': {
    group: 'Working', size: 'large', activityLevel: 4,
    walkMinsPerDay: 60, idealWalksPerDay: 2,
    weightRangeKg: [35, 45], caloriesPerKgBase: 58,
    coat: 'Short, smooth, pure white',
    temperament: 'Loyal, cheerful, friendly to family, protective',
    traits: ['Powerful athlete', 'Devoted companion', 'Needs socialization from a young age'],
    healthNotes: 'Deafness (especially white dogs). Hip dysplasia. Sunburn risk on white skin.',
    feedingNotes: 'High-protein athletic diet needed. Adjust for activity.',
    originalPurpose: 'Big game hunting (pumas)',
    fun: 'Banned in some countries including the UK under Dangerous Dogs Act.',
  },

  // ── TERRIER ───────────────────────────────────────────
  'Jack Russell Terrier': {
    group: 'Terrier', size: 'small', activityLevel: 5,
    walkMinsPerDay: 60, idealWalksPerDay: 2,
    weightRangeKg: [6, 8], caloriesPerKgBase: 80,
    coat: 'Smooth or rough, white with black/tan markings',
    temperament: 'Energetic, feisty, fearless, intelligent',
    traits: ['Big dog in a tiny body', 'Loves to dig', 'Very fast', 'Stubborn'],
    healthNotes: 'Generally very healthy. Lens luxation (eye). Legg-Calvé-Perthes disease.',
    feedingNotes: 'High metabolism — needs dense, quality food for their size. Don\'t overfeed.',
    originalPurpose: 'Fox hunting',
    fun: 'Despite tiny size, Jack Russells are fearless enough to take on foxes underground.',
  },
  'Bull Terrier': {
    group: 'Terrier', size: 'medium', activityLevel: 4,
    walkMinsPerDay: 60, idealWalksPerDay: 2,
    weightRangeKg: [18, 30], caloriesPerKgBase: 65,
    coat: 'Short, flat, glossy, white or coloured',
    temperament: 'Mischievous, feisty, playful, loyal',
    traits: ['Egg-shaped head is unique', 'Very playful and clownish', 'Stubborn', 'Loves people'],
    healthNotes: 'Deafness (white dogs). Kidney and heart conditions. Obsessive-compulsive behaviours.',
    feedingNotes: 'Food-motivated breed. Quality protein diet. Two meals per day.',
    originalPurpose: 'Bull-baiting and dog fighting (historical)',
    fun: 'The Target mascot dog "Bullseye" is a Bull Terrier!',
  },
  'Staffordshire Bull Terrier': {
    group: 'Terrier', size: 'medium', activityLevel: 4,
    walkMinsPerDay: 60, idealWalksPerDay: 2,
    weightRangeKg: [11, 17], caloriesPerKgBase: 68,
    coat: 'Smooth, short, various colours',
    temperament: 'Courageous, tenacious, affectionate, loyal',
    traits: ['Incredible with children — nicknamed "nanny dog"', 'Muscular', 'Loves people', 'Stubborn'],
    healthNotes: 'L-2-HGA and HC (hereditary cataract) — DNA test parents. Skin conditions.',
    feedingNotes: 'Muscular breed benefits from protein-rich food. Split into 2 meals.',
    originalPurpose: 'Dog fighting (historical)',
    fun: 'Despite a tough history, Staffies are consistently rated one of the best family dogs.',
  },
  'West Highland White Terrier': {
    group: 'Terrier', size: 'small', activityLevel: 3,
    walkMinsPerDay: 45, idealWalksPerDay: 2,
    weightRangeKg: [6, 10], caloriesPerKgBase: 78,
    coat: 'Dense, harsh white double coat',
    temperament: 'Happy, curious, active, friendly',
    traits: ['Very spunky', 'Good apartment dog', 'Bold', 'Alert'],
    healthNotes: 'White Shaker Syndrome. Skin conditions (atopic dermatitis). Lionjaw (CMO).',
    feedingNotes: 'Small dog — measure food carefully. High-quality sensitive skin formulas often recommended.',
    originalPurpose: 'Ratting and fox hunting in Scotland',
    fun: 'Westies appear on the famous Black & White Scotch Whisky bottle!',
  },
  'Scottish Terrier': {
    group: 'Terrier', size: 'small', activityLevel: 3,
    walkMinsPerDay: 45, idealWalksPerDay: 2,
    weightRangeKg: [8, 10], caloriesPerKgBase: 76,
    coat: 'Wiry outer coat, soft undercoat, black or wheaten',
    temperament: 'Independent, feisty, spirited, loyal',
    traits: ['Very independent', 'Dignified', 'Stubborn but loveable', 'Loves to dig'],
    healthNotes: 'Scottie cramp (movement disorder). Bladder cancer predisposition.',
    feedingNotes: 'Small appetite but high-quality food essential. Avoid obesity.',
    originalPurpose: 'Badger and fox hunting in Scotland',
    fun: 'US Presidents FDR and George W. Bush both owned Scottish Terriers in the White House.',
  },
  'Yorkshire Terrier': {
    group: 'Terrier', size: 'small', activityLevel: 3,
    walkMinsPerDay: 30, idealWalksPerDay: 2,
    weightRangeKg: [2, 3.2], caloriesPerKgBase: 88,
    coat: 'Long, silky, fine, steel blue and tan',
    temperament: 'Feisty, brave, bossy, affectionate',
    traits: ['Tiny but thinks they\'re massive', 'Big personality', 'Good apartment dog', 'Hypoallergenic-ish'],
    healthNotes: 'Patellar luxation, tracheal collapse, Porto-systemic shunt.',
    feedingNotes: 'Tiny portions — easily overfed. Small-breed specific kibble recommended.',
    originalPurpose: 'Rat catching in Yorkshire mills',
    fun: 'A Yorkie named Smoky served in WWII and was reportedly the first therapy dog.',
  },

  // ── HOUND ─────────────────────────────────────────────
  'Beagle': {
    group: 'Hound', size: 'medium', activityLevel: 4,
    walkMinsPerDay: 60, idealWalksPerDay: 2,
    weightRangeKg: [9, 11], caloriesPerKgBase: 72,
    coat: 'Short, dense, tricolour',
    temperament: 'Merry, curious, friendly, loving',
    traits: ['Nose always to the ground', 'Will follow any scent — needs lead', 'Vocal (howls)', 'Food-obsessed'],
    healthNotes: 'Epilepsy common. Hypothyroidism. Weight gain if inactive.',
    feedingNotes: 'Extremely food motivated — prone to obesity. Measured meals essential.',
    originalPurpose: 'Rabbit hunting',
    fun: 'Snoopy from Peanuts is a Beagle!',
  },
  'Basset Hound': {
    group: 'Hound', size: 'medium', activityLevel: 2,
    walkMinsPerDay: 30, idealWalksPerDay: 2,
    weightRangeKg: [20, 30], caloriesPerKgBase: 52,
    coat: 'Short, smooth, tricolour',
    temperament: 'Charming, patient, low-key, gentle',
    traits: ['Incredible nose (2nd only to Bloodhound)', 'Stubborn on walks', 'Lazy indoors', 'Prone to wandering'],
    healthNotes: 'Obesity is the biggest health concern. Back problems from long spine. Ear infections.',
    feedingNotes: 'Monitor weight very carefully — this breed will eat everything. Controlled portions.',
    originalPurpose: 'Rabbit and hare hunting',
    fun: 'Their long ears help to sweep scent particles upward to their nose.',
  },
  'Bloodhound': {
    group: 'Hound', size: 'large', activityLevel: 4,
    walkMinsPerDay: 60, idealWalksPerDay: 2,
    weightRangeKg: [36, 50], caloriesPerKgBase: 52,
    coat: 'Short, loose, red, liver/tan or black/tan',
    temperament: 'Stubborn, gentle, even-tempered, affectionate',
    traits: ['World\'s best nose — can track a 300-hour-old scent', 'Very stubborn on a lead', 'Drools extensively'],
    healthNotes: 'Bloat, hip/elbow dysplasia. Ear infections from floppy ears.',
    feedingNotes: 'Large breed — 2 meals per day. Avoid exercise right after feeding.',
    originalPurpose: 'Tracking humans and game by scent',
    fun: 'Bloodhound evidence is legally admissible in US courts — that\'s how reliable their nose is.',
  },
  'Dachshund': {
    group: 'Hound', size: 'small', activityLevel: 3,
    walkMinsPerDay: 45, idealWalksPerDay: 2,
    weightRangeKg: [4, 15], caloriesPerKgBase: 75,
    coat: 'Smooth, wirehaired or longhaired, various colours',
    temperament: 'Clever, lively, courageous with stubbornness',
    traits: ['Hot-dog shape is beloved worldwide', 'Very stubborn', 'Loves to burrow', 'Vocal'],
    healthNotes: 'Intervertebral disc disease (IVDD) is the main concern — avoid jumping.',
    feedingNotes: 'Prone to obesity which worsens back problems. Strict portion control.',
    originalPurpose: 'Badger hunting underground',
    fun: 'The German word "Dackel" means "badger dog." They were bred specifically to hunt badgers underground.',
  },
  'Whippet': {
    group: 'Hound', size: 'medium', activityLevel: 4,
    walkMinsPerDay: 60, idealWalksPerDay: 2,
    weightRangeKg: [12, 18], caloriesPerKgBase: 68,
    coat: 'Short, fine, smooth',
    temperament: 'Gentle, playful, calm indoors, affectionate',
    traits: ['Sprinter — incredibly fast in short bursts', 'Calm couch potato at home', 'Sensitive'],
    healthNotes: 'Generally very healthy. Sensitive to anesthesia. No cold weather tolerance.',
    feedingNotes: 'Lean breed — monitor weight. High-quality protein for muscle maintenance.',
    originalPurpose: 'Rabbit coursing and racing',
    fun: 'Can reach speeds of 35 mph making them one of the fastest dog breeds.',
  },
  'Greyhound': {
    group: 'Hound', size: 'large', activityLevel: 3,
    walkMinsPerDay: 45, idealWalksPerDay: 2,
    weightRangeKg: [27, 40], caloriesPerKgBase: 55,
    coat: 'Short, fine, smooth',
    temperament: 'Gentle, independent, noble, affectionate with family',
    traits: ['40-45mph top speed', 'Lazy couch potatoes at home', 'Often ex-racing dogs', 'Sensitive'],
    healthNotes: 'Osteosarcoma risk. Sensitive to anesthesia. Thin skin — injury-prone.',
    feedingNotes: 'Lean dogs need monitored diet. 2 small meals to reduce bloat risk.',
    originalPurpose: 'Coursing game, racing',
    fun: 'Despite being the fastest dog, they sleep up to 18 hours a day!',
  },
  'Afghan Hound': {
    group: 'Hound', size: 'large', activityLevel: 4,
    walkMinsPerDay: 60, idealWalksPerDay: 2,
    weightRangeKg: [23, 27], caloriesPerKgBase: 58,
    coat: 'Long, silky, flowing coat in any colour',
    temperament: 'Aloof, dignified, independent, clownish at home',
    traits: ['Supermodel looks', 'Very independent', 'Difficult to train', 'Cat-like personality'],
    healthNotes: 'Hypothyroidism, juvenile cataracts, hip dysplasia.',
    feedingNotes: 'Lean build — quality protein to maintain muscle tone.',
    originalPurpose: 'Hunting large prey in Afghanistan mountains',
    fun: 'The world\'s first cloned dog was an Afghan Hound named Snuppy, cloned in South Korea in 2005.',
  },
  'Saluki': {
    group: 'Hound', size: 'large', activityLevel: 5,
    walkMinsPerDay: 90, idealWalksPerDay: 2,
    weightRangeKg: [16, 29], caloriesPerKgBase: 62,
    coat: 'Silky, feathered ears and tail, short on body',
    temperament: 'Gentle, devoted, reserved, sensitive',
    traits: ['Ancient breed', 'Extremely fast', 'Independent', 'Very sensitive temperament'],
    healthNotes: 'Cardiac disease. Sensitive to anaesthesia.',
    feedingNotes: 'High energy sprinter — quality protein and fat. Monitor for being underweight.',
    originalPurpose: 'Gazelle hunting in the Middle East',
    fun: 'One of the oldest dog breeds — Saluki remains found in Sumerian carvings dating to 7000 BC.',
  },
  'Basenji': {
    group: 'Hound', size: 'small', activityLevel: 4,
    walkMinsPerDay: 60, idealWalksPerDay: 2,
    weightRangeKg: [9, 11], caloriesPerKgBase: 72,
    coat: 'Short, smooth, tricolour, black and white',
    temperament: 'Alert, curious, energetic, affectionate',
    traits: ['Does not bark — yodels instead', 'Cat-like self-grooming', 'Escape artist', 'Independent'],
    healthNotes: 'Fanconi syndrome (kidney disorder). Progressive retinal atrophy.',
    feedingNotes: 'Small but energetic. High-quality small-breed food.',
    originalPurpose: 'Hunting in Central Africa',
    fun: 'The only dog breed that cannot bark — they make a yodel-like sound instead.',
  },
  'Rhodesian Ridgeback': {
    group: 'Hound', size: 'large', activityLevel: 4,
    walkMinsPerDay: 60, idealWalksPerDay: 2,
    weightRangeKg: [29, 41], caloriesPerKgBase: 58,
    coat: 'Short, dense, wheaten',
    temperament: 'Loyal, affectionate, dignified, stubborn',
    traits: ['Distinctive ridge of reversed hair on back', 'Were used to track lions', 'Strong willed'],
    healthNotes: 'Hip dysplasia. Dermoid sinus (neurological).',
    feedingNotes: 'Athletic build — protein-rich diet. 2 meals per day.',
    originalPurpose: 'Tracking lions in southern Africa',
    fun: 'The ridge on their back is reversed hair that grows towards the head — not just a marking, it\'s a physical trait.',
  },
  'Irish Wolfhound': {
    group: 'Hound', size: 'giant', activityLevel: 3,
    walkMinsPerDay: 60, idealWalksPerDay: 2,
    weightRangeKg: [48, 70], caloriesPerKgBase: 44,
    coat: 'Rough, hard, grey/brindle/red/black/white',
    temperament: 'Patient, thoughtful, generous, loyal',
    traits: ['Tallest dog breed', 'Gentle giant', 'Short lifespan (6-8 years)', 'Calm nature'],
    healthNotes: 'Cardiomyopathy, bone cancer, bloat. Tragically short lifespan.',
    feedingNotes: 'Giant breed — feed 2 meals/day. Joint supplements from early age.',
    originalPurpose: 'Wolf and Irish elk hunting',
    fun: 'Can look a human in the eye while standing — they are the tallest dog breed in the world.',
  },
  'Italian Greyhound': {
    group: 'Hound', size: 'small', activityLevel: 3,
    walkMinsPerDay: 45, idealWalksPerDay: 2,
    weightRangeKg: [3.6, 5], caloriesPerKgBase: 80,
    coat: 'Extremely short, glossy, fine',
    temperament: 'Playful, alert, sensitive, affectionate',
    traits: ['Miniature greyhound', 'Freeze in cold weather — needs coats', 'Fragile legs', 'Velcro to owner'],
    healthNotes: 'Leg fractures very common. Retained baby teeth. Epilepsy.',
    feedingNotes: 'Very small — careful portion control. Small-breed specific food.',
    originalPurpose: 'Companion dog to nobility',
    fun: 'Were said to be the favourite dogs of Renaissance-era royal courts.',
  },

  // ── NON-SPORTING / COMPANION ──────────────────────────
  'Bulldog': {
    group: 'Non-Sporting', size: 'medium', activityLevel: 2,
    walkMinsPerDay: 30, idealWalksPerDay: 2,
    weightRangeKg: [18, 25], caloriesPerKgBase: 50,
    coat: 'Short, smooth, fine',
    temperament: 'Docile, friendly, willful, courageous',
    traits: ['Iconic wrinkled face', 'Loves lounging', 'Heat intolerant', 'Snores a lot'],
    healthNotes: 'Brachycephalic — airway issues. Never walk in hot weather. Hip dysplasia. Skin fold infections.',
    feedingNotes: 'Prone to obesity — strict portion control. Slow feeder bowls help.',
    originalPurpose: 'Bull-baiting (historical)',
    fun: 'Despite looking fierce, Bulldogs are one of the most docile and gentle breeds.',
  },
  'French Bulldog': {
    group: 'Non-Sporting', size: 'small', activityLevel: 2,
    walkMinsPerDay: 30, idealWalksPerDay: 2,
    weightRangeKg: [8, 14], caloriesPerKgBase: 65,
    coat: 'Short, fine, smooth, various colours',
    temperament: 'Playful, adaptable, smart, affectionate',
    traits: ['Great city dog', 'Bat ears are adorable', 'Brachycephalic', 'Loves attention'],
    healthNotes: 'Serious breathing issues due to flat face. Cannot swim. Spine problems. Expensive vet bills.',
    feedingNotes: 'Carefully monitor weight. Feed twice daily. Avoid overheating when feeding.',
    originalPurpose: 'Companion',
    fun: 'Most popular breed in the UK and US. Their farts are legendary.',
  },
  'Dalmatian': {
    group: 'Non-Sporting', size: 'large', activityLevel: 5,
    walkMinsPerDay: 90, idealWalksPerDay: 2,
    weightRangeKg: [23, 32], caloriesPerKgBase: 62,
    coat: 'Short, dense, white with black or liver spots',
    temperament: 'Outgoing, energetic, playful, sensitive',
    traits: ['Born white — spots appear at 3 weeks', 'Very high energy', 'Can be deaf (esp. blue eyes)', 'Loyal'],
    healthNotes: 'Deafness common — BAER test puppies. Urinary stones (unique uric acid metabolism).',
    feedingNotes: 'Low-purine diet essential to prevent urinary stones. Avoid organ meats.',
    originalPurpose: 'Carriage dog, firehouse dog',
    fun: 'Disney\'s 101 Dalmatians increased breed popularity so much it caused massive welfare problems.',
  },
  'Boston Terrier': {
    group: 'Non-Sporting', size: 'small', activityLevel: 3,
    walkMinsPerDay: 45, idealWalksPerDay: 2,
    weightRangeKg: [5, 11], caloriesPerKgBase: 76,
    coat: 'Short, smooth, black/white or brindle/white',
    temperament: 'Friendly, bright, adaptable, amusing',
    traits: ['Tuxedo-like markings', 'Brachycephalic', 'Apartment-friendly', 'Very people-oriented'],
    healthNotes: 'Eye issues (corneal ulcers). Breathing problems. Deafness in white gene.',
    feedingNotes: 'Small breed — small kibble. Monitor weight.',
    originalPurpose: 'Companion',
    fun: 'First American-bred breed to be recognised by the AKC. Nicknamed the "American Gentleman."',
  },
  'Shiba Inu': {
    group: 'Non-Sporting', size: 'medium', activityLevel: 4,
    walkMinsPerDay: 60, idealWalksPerDay: 2,
    weightRangeKg: [8, 11], caloriesPerKgBase: 70,
    coat: 'Double coat, stiff outer, soft inner, red/black/sesame',
    temperament: 'Alert, active, spirited, faithful',
    traits: ['Doge meme breed!', 'Cat-like independence', 'Very clean', 'The "Shiba scream"'],
    healthNotes: 'Hip dysplasia, eye conditions. Allergies.',
    feedingNotes: 'Can be picky eaters. High-quality protein-based kibble.',
    originalPurpose: 'Hunting small game in mountainous Japan',
    fun: 'Part of the famous "doge" meme. Also the mascot of Dogecoin cryptocurrency.',
  },
  'Pug': {
    group: 'Non-Sporting', size: 'small', activityLevel: 2,
    walkMinsPerDay: 25, idealWalksPerDay: 2,
    weightRangeKg: [6, 8], caloriesPerKgBase: 68,
    coat: 'Fine, short, smooth, fawn or black',
    temperament: 'Charming, mischievous, loving, playful',
    traits: ['Brachycephalic — serious breathing issues', 'Wrinkly and loveable', 'Excellent companion'],
    healthNotes: 'Pug Dog Encephalitis (fatal brain disease). Eye problems. BOAS (breathing disorder). Heat stroke risk.',
    feedingNotes: 'Very prone to obesity — strict portions essential. Avoid overexertion in heat.',
    originalPurpose: 'Companion to Chinese emperors',
    fun: 'A group of Pugs is called a "grumble."',
  },

  // ── TOY ───────────────────────────────────────────────
  'Chihuahua': {
    group: 'Toy', size: 'small', activityLevel: 3,
    walkMinsPerDay: 30, idealWalksPerDay: 2,
    weightRangeKg: [1.5, 3], caloriesPerKgBase: 100,
    coat: 'Smooth or long coat, any colour',
    temperament: 'Charming, graceful, sassy, loyal',
    traits: ['World\'s smallest dog', 'Big personality', 'Loyal to one person', 'Prone to shivering'],
    healthNotes: 'Molera (fontanelle in skull). Hypoglycemia. Patellar luxation. Tracheal collapse.',
    feedingNotes: 'Tiny stomach — feed little and often. High-quality small-breed food.',
    originalPurpose: 'Sacred companion to ancient Aztecs',
    fun: 'Despite their size, Chihuahuas have the biggest brain relative to body size of all dog breeds.',
  },
  'Cavalier King Charles Spaniel': {
    group: 'Toy', size: 'small', activityLevel: 3,
    walkMinsPerDay: 45, idealWalksPerDay: 2,
    weightRangeKg: [5, 8], caloriesPerKgBase: 76,
    coat: 'Long, silky, wavy, tricolour/Blenheim/ruby/black-tan',
    temperament: 'Gentle, affectionate, graceful, fearless',
    traits: ['Gentle and loving', 'Great with children', 'Velcro dog', 'Loves cuddles'],
    healthNotes: 'Mitral Valve Disease affects almost all Cavaliers by age 5. Syringomyelia (skull too small for brain) — serious welfare concern.',
    feedingNotes: 'Moderate appetite. High-quality food supporting heart health.',
    originalPurpose: 'Royal companion dog',
    fun: 'King Charles II was never seen without his spaniels — he even slept with them.',
  },
  'Maltese': {
    group: 'Toy', size: 'small', activityLevel: 2,
    walkMinsPerDay: 30, idealWalksPerDay: 2,
    weightRangeKg: [1.8, 3.2], caloriesPerKgBase: 92,
    coat: 'Long, silky, pure white',
    temperament: 'Gentle, playful, charming, responsive',
    traits: ['Ancient companion breed', 'Hypoallergenic-ish', 'Bold for their size'],
    healthNotes: 'Patellar luxation, collapsed trachea, dental disease.',
    feedingNotes: 'Tiny portions — 2-3 small meals. Small-breed specific nutrition.',
    originalPurpose: 'Companion to aristocracy for 3,000 years',
    fun: 'Aristotle called the Maltese "perfectly proportioned" dogs.',
  },
  'Pomeranian': {
    group: 'Toy', size: 'small', activityLevel: 3,
    walkMinsPerDay: 30, idealWalksPerDay: 2,
    weightRangeKg: [1.9, 3.5], caloriesPerKgBase: 88,
    coat: 'Double coat, fluffy, various colours',
    temperament: 'Lively, bold, inquisitive, friendly',
    traits: ['Foxy little face', 'Thinks it\'s a big dog', 'Bold', 'Very vocal'],
    healthNotes: 'Tracheal collapse, patellar luxation, dental disease.',
    feedingNotes: 'Tiny but energetic. Small-breed food, carefully measured.',
    originalPurpose: 'Companion, descended from large sled dogs',
    fun: 'Two Pomeranians survived the Titanic sinking, brought on lifeboats by their owners.',
  },
  'Papillon': {
    group: 'Toy', size: 'small', activityLevel: 4,
    walkMinsPerDay: 45, idealWalksPerDay: 2,
    weightRangeKg: [3.2, 4.5], caloriesPerKgBase: 82,
    coat: 'Long, flowing, silky, white with patches',
    temperament: 'Friendly, alert, happy, energetic',
    traits: ['Butterfly ears', 'Highly intelligent — one of sharpest small breeds', 'Fast and agile'],
    healthNotes: 'Patellar luxation. Fontanelle in some lines.',
    feedingNotes: 'Small but active — quality small-breed food.',
    originalPurpose: 'Companion to European nobility',
    fun: '"Papillon" means butterfly in French — after their wing-like ears.',
  },

  // ── PASTORAL / MISC ───────────────────────────────────
  'Boxer': {
    group: 'Working', size: 'large', activityLevel: 4,
    walkMinsPerDay: 60, idealWalksPerDay: 2,
    weightRangeKg: [25, 36], caloriesPerKgBase: 62,
    coat: 'Short, shiny, fawn or brindle',
    temperament: 'Fun, bright, active, loyal',
    traits: ['Eternal puppies', 'Great with children', 'Devoted family dog', 'Brachycephalic'],
    healthNotes: 'High cancer rates. Heart conditions (ARVC). Brachycephalic syndrome. Bloat.',
    feedingNotes: 'Feed twice daily. Slow feeder to prevent bloat. Quality protein diet.',
    originalPurpose: 'Hunting, guarding, police/military',
    fun: 'Boxers hold the world record for the longest tongue of any dog — 17 inches!',
  },
  'Shih Tzu': {
    group: 'Toy', size: 'small', activityLevel: 2,
    walkMinsPerDay: 30, idealWalksPerDay: 2,
    weightRangeKg: [4, 7], caloriesPerKgBase: 78,
    coat: 'Long, dense, slightly wavy double coat',
    temperament: 'Playful, outgoing, alert, lively',
    traits: ['Former Chinese royal companion', 'Doesn\'t shed much', 'Brachycephalic', 'Sociable'],
    healthNotes: 'Eye problems, dental disease, breathing issues. Heat intolerant.',
    feedingNotes: 'Small portions twice daily. Dental hygiene important — wet food can help.',
    originalPurpose: 'Lapdog for Chinese emperors',
    fun: 'Shih Tzu means "lion dog" in Mandarin. Ming Dynasty emperors treasured them.',
  },
  'Bichon Frise': {
    group: 'Non-Sporting', size: 'small', activityLevel: 3,
    walkMinsPerDay: 30, idealWalksPerDay: 2,
    weightRangeKg: [5, 10], caloriesPerKgBase: 78,
    coat: 'Curly, puffy, white',
    temperament: 'Playful, curious, peppy, affectionate',
    traits: ['Hypoallergenic', 'Loves people', 'Good apartment dog', 'Cheerful'],
    healthNotes: 'Allergies and skin conditions common. Patellar luxation.',
    feedingNotes: 'Small-breed food. Monitor for food sensitivities.',
    originalPurpose: 'Companion aboard Spanish sailing ships',
    fun: 'Bichons were used as circus performers in France in the 19th century.',
  },
  'Havanese': {
    group: 'Toy', size: 'small', activityLevel: 3,
    walkMinsPerDay: 30, idealWalksPerDay: 2,
    weightRangeKg: [3, 6], caloriesPerKgBase: 78,
    coat: 'Long, soft, silky, any colour',
    temperament: 'Playful, intelligent, companionable, gentle',
    traits: ['Cuba\'s national dog', 'Loves to show off', 'Trainable', 'Velcro to owner'],
    healthNotes: 'Chondrodysplasia, deafness, cataracts.',
    feedingNotes: 'Small portions twice daily. Feed a complete small-breed diet.',
    originalPurpose: 'Companion to Cuban aristocracy',
    fun: 'The only dog breed native to Cuba — the national dog of Cuba.',
  },
  'Lhasa Apso': {
    group: 'Non-Sporting', size: 'small', activityLevel: 2,
    walkMinsPerDay: 30, idealWalksPerDay: 2,
    weightRangeKg: [5, 8], caloriesPerKgBase: 75,
    coat: 'Heavy, straight, hard, floor-length',
    temperament: 'Assertive, playful, smart, comical',
    traits: ['Ancient Tibetan sentinel', 'Suspicious of strangers', 'Very long-lived (15-18 years)', 'Independent'],
    healthNotes: 'Kidney problems (renal dysplasia). Eye conditions. Patellar luxation.',
    feedingNotes: 'Low to moderate caloric needs. Quality small-breed food.',
    originalPurpose: 'Sentinel dog in Tibetan Buddhist monasteries',
    fun: 'The Dalai Lama would gift Lhasa Apsos to emperors — they were considered sacred.',
  },
  'Miniature Schnauzer': {
    group: 'Terrier', size: 'small', activityLevel: 4,
    walkMinsPerDay: 45, idealWalksPerDay: 2,
    weightRangeKg: [5, 8], caloriesPerKgBase: 78,
    coat: 'Wiry, hard outer, soft undercoat, salt & pepper/black/silver',
    temperament: 'Alert, spirited, smart, friendly',
    traits: ['Bushy beard and eyebrows', 'Very smart and easy to train', 'Loves to bark', 'Sociable'],
    healthNotes: 'Pancreatitis — avoid high-fat foods. Bladder stones. Hyperlipidemia.',
    feedingNotes: 'Low-fat diet to prevent pancreatitis. Feed twice daily. Avoid fatty treats.',
    originalPurpose: 'Ratting on farms',
    fun: 'The most popular Schnauzer size worldwide.',
  },
  'Springer Spaniel': {
    group: 'Sporting', size: 'medium', activityLevel: 5,
    walkMinsPerDay: 90, idealWalksPerDay: 2,
    weightRangeKg: [18, 25], caloriesPerKgBase: 65,
    coat: 'Medium-length, wavy, liver and white or black and white',
    temperament: 'Friendly, playful, obedient, active',
    traits: ['Endless energy', 'Great family dog', 'Excellent working dog', 'Love water'],
    healthNotes: 'Hip dysplasia, ear infections (floppy ears), eye conditions. "Rage syndrome" in some lines.',
    feedingNotes: 'Active breed — high-energy food. May need 1200-1500 kcal on active days.',
    originalPurpose: 'Flushing and retrieving game birds',
    fun: 'Can flush game at full sprint — one of the most energetic breeds in the world.',
  },
  'Cocker Spaniel': {
    group: 'Sporting', size: 'medium', activityLevel: 3,
    walkMinsPerDay: 45, idealWalksPerDay: 2,
    weightRangeKg: [11, 15], caloriesPerKgBase: 68,
    coat: 'Silky, flat or wavy, various colours',
    temperament: 'Happy, smart, gentle, trainable',
    traits: ['Beautiful long ears', 'Loves to sniff and explore', 'Gentle nature', 'Good family dog'],
    healthNotes: 'Ear infections very common (floppy ears trap moisture). Eye conditions. Hip dysplasia.',
    feedingNotes: 'Quality protein-based diet. Watch for weight gain.',
    originalPurpose: 'Flushing and retrieving woodcocks (hence "Cocker")',
    fun: 'Lady in Disney\'s Lady and the Tramp is an American Cocker Spaniel.',
  },
  'Bernese Mountain Dog': {
    group: 'Working', size: 'large', activityLevel: 3,
    walkMinsPerDay: 60, idealWalksPerDay: 2,
    weightRangeKg: [32, 52], caloriesPerKgBase: 50,
    coat: 'Tri-coloured (black, white, rust), thick double coat',
    temperament: 'Calm, good-natured, patient, devoted',
    traits: ['Stunning tri-colour coat', 'Gentle giant', 'Loves cold weather', 'Great draft dog'],
    healthNotes: 'High cancer rates. Hip and elbow dysplasia. Short lifespan (7-8 years).',
    feedingNotes: 'Large breed food from puppyhood (controls growth). Joint supplements recommended.',
    originalPurpose: 'Draft and droving dog in Swiss Alps',
    fun: 'Named after the Swiss city of Bern. Their German name "Berner Sennenhund" means "Bernese Alpine Herdsman\'s Dog."',
  },

  // ── POPULAR MIXED BREEDS ──────────────────────────────
  'Goldendoodle': {
    group: 'Mixed Breed (Golden Retriever × Poodle)', size: 'medium',
    activityLevel: 4, walkMinsPerDay: 60, idealWalksPerDay: 2,
    weightRangeKg: [13, 35], caloriesPerKgBase: 60,
    coat: 'Wavy to curly, low-shedding, golden/cream/apricot',
    temperament: 'Friendly, patient, loving, playful, easy-going',
    traits: ['Low-shedding (great for allergies)', 'Highly intelligent', 'Gentle with children', 'Loves everyone', 'Adaptable to apartments or houses'],
    healthNotes: 'Hip dysplasia possible from both parents. Progressive retinal atrophy (PRA). Subvalvular aortic stenosis. Generally healthier than purebreds due to hybrid vigour.',
    feedingNotes: 'Adjust portions based on size (mini vs standard varies hugely). High-quality protein-first diet. Avoid grain-free diets linked to DCM heart disease.',
    originalPurpose: 'Hypoallergenic family companion',
    fun: 'One of the most popular "designer dogs" in the world. Wally Conron created the first Labradoodle (not Goldendoodle) for a guide dog need — the Goldendoodle followed soon after.',
    sizes: 'Come in mini (7-16kg), medium (16-25kg) and standard (25-35kg)',
  },
  'Labradoodle': {
    group: 'Mixed Breed (Labrador × Poodle)', size: 'large',
    activityLevel: 4, walkMinsPerDay: 60, idealWalksPerDay: 2,
    weightRangeKg: [23, 35], caloriesPerKgBase: 58,
    coat: 'Wavy or curly, low to non-shedding, various colours',
    temperament: 'Sociable, active, friendly, intuitive, gentle',
    traits: ['Original "designer dog"', 'Guide dog and therapy dog popular', 'Loves water', 'Trainable'],
    healthNotes: 'Hip dysplasia from Labrador side. Eye conditions from Poodle side. Generally healthy.',
    feedingNotes: 'Active dogs — quality protein diet. Split into 2 meals. Monitor weight (food-motivated like Labs).',
    originalPurpose: 'Hypoallergenic guide dog',
    fun: 'The Labradoodle was created in 1989 by Wally Conron for a blind woman whose husband was allergic to dogs.',
  },
  'Cavapoo': {
    group: 'Mixed Breed (Cavalier King Charles Spaniel × Poodle)', size: 'small',
    activityLevel: 3, walkMinsPerDay: 45, idealWalksPerDay: 2,
    weightRangeKg: [5, 11], caloriesPerKgBase: 72,
    coat: 'Soft, wavy to curly, low-shedding, various colours',
    temperament: 'Loving, gentle, playful, adaptable, sociable',
    traits: ['Perfect apartment dog', 'Great for first-time owners', 'Loves cuddles', 'Velcro dog'],
    healthNotes: 'Inherits Cavalier\'s heart disease risk. PRA from Poodle. Generally healthier than pure Cavaliers.',
    feedingNotes: 'Small breed — measured portions twice daily. Quality small-breed food.',
    originalPurpose: 'Companion',
    fun: 'Consistently voted one of the most popular crossbreeds in the UK.',
  },
  'Cockapoo': {
    group: 'Mixed Breed (Cocker Spaniel × Poodle)', size: 'small',
    activityLevel: 3, walkMinsPerDay: 45, idealWalksPerDay: 2,
    weightRangeKg: [5, 11], caloriesPerKgBase: 72,
    coat: 'Wavy or curly, low-shedding',
    temperament: 'Merry, outgoing, friendly, curious',
    traits: ['One of oldest designer breeds (1960s USA)', 'Low shedding', 'Great family dog'],
    healthNotes: 'Ear infections (floppy ears). Hip dysplasia. Eye conditions from Cocker Spaniel side.',
    feedingNotes: 'Small-breed food twice daily. Watch for weight gain.',
    originalPurpose: 'Companion',
    fun: 'The first "doodle" — Cockapoos were being bred as early as the 1960s.',
  },
  'Bernedoodle': {
    group: 'Mixed Breed (Bernese Mountain Dog × Poodle)', size: 'large',
    activityLevel: 3, walkMinsPerDay: 60, idealWalksPerDay: 2,
    weightRangeKg: [22, 45], caloriesPerKgBase: 55,
    coat: 'Wavy or curly, low-shedding, tri-colour or bicolour',
    temperament: 'Gentle, smart, playful, loyal, goofy',
    traits: ['Stunning tri-colour coats', 'Gentler than Goldendoodles', 'Loves cold weather', 'Calm temperament'],
    healthNotes: 'Lower cancer risk than pure Bernese. Hip dysplasia possible. Generally excellent health.',
    feedingNotes: 'Large breed — quality protein diet. 2 meals. Monitor weight.',
    originalPurpose: 'Companion',
    fun: 'Often described as having "the perfect temperament" — fun and playful but calm.',
  },
  'Aussiedoodle': {
    group: 'Mixed Breed (Australian Shepherd × Poodle)', size: 'medium',
    activityLevel: 5, walkMinsPerDay: 75, idealWalksPerDay: 2,
    weightRangeKg: [14, 27], caloriesPerKgBase: 65,
    coat: 'Wavy, low-shedding, merle or solid colours',
    temperament: 'Energetic, intelligent, loyal, fun-loving',
    traits: ['Very smart from both parents', 'Loves to work and learn', 'Merle coats are stunning'],
    healthNotes: 'MDR1 gene (check before medications). Hip dysplasia. Generally healthy.',
    feedingNotes: 'Active breed — higher calorie needs. Quality protein. Adjust for activity.',
    originalPurpose: 'Active family companion',
    fun: 'One of the quickest breeds to learn new tricks — combines Aussie intelligence with Poodle smarts.',
  },
  'Sheepadoodle': {
    group: 'Mixed Breed (Old English Sheepdog × Poodle)', size: 'large',
    activityLevel: 4, walkMinsPerDay: 60, idealWalksPerDay: 2,
    weightRangeKg: [27, 45], caloriesPerKgBase: 55,
    coat: 'Fluffy, wavy, low-shedding, black and white',
    temperament: 'Gentle, smart, playful, loving',
    traits: ['Teddy bear in real life', 'Great with children', 'Calm nature with good exercise'],
    healthNotes: 'Hip dysplasia from both sides. Bloat possible. Generally healthy.',
    feedingNotes: 'Large breed twice daily feeding. High-quality food.',
    originalPurpose: 'Companion',
    fun: 'Sheepadoodles gain social media fame for looking exactly like giant stuffed animals.',
  },
  'Maltipoo': {
    group: 'Mixed Breed (Maltese × Poodle)', size: 'small',
    activityLevel: 2, walkMinsPerDay: 30, idealWalksPerDay: 2,
    weightRangeKg: [2, 5], caloriesPerKgBase: 88,
    coat: 'Soft, wavy to curly, white or cream',
    temperament: 'Playful, charming, gentle, people-oriented',
    traits: ['Tiny and fluffy', 'Great for apartments', 'Hypoallergenic', 'Velcro dog'],
    healthNotes: 'Patellar luxation, dental disease (tiny teeth). Epilepsy from Maltese side.',
    feedingNotes: 'Very small — tiny but frequent meals. Small-breed specific nutrition.',
    originalPurpose: 'Companion',
    fun: 'One of the most popular celebrity dogs — owned by many Hollywood stars.',
  },
  'Pomsky': {
    group: 'Mixed Breed (Pomeranian × Siberian Husky)', size: 'small',
    activityLevel: 4, walkMinsPerDay: 60, idealWalksPerDay: 2,
    weightRangeKg: [7, 14], caloriesPerKgBase: 70,
    coat: 'Medium length, fluffy, Husky-like colouring',
    temperament: 'Energetic, playful, intelligent, attention-seeking',
    traits: ['Mini Husky appearance', 'Very photogenic', 'Vocal', 'Smart but stubborn'],
    healthNotes: 'Eye conditions from both parents. Hip dysplasia. Can inherit Husky energy.',
    feedingNotes: 'Moderate feeder. Quality small/medium breed food.',
    originalPurpose: 'Companion',
    fun: 'Created via artificial insemination (given size mismatch). Went viral on social media in 2012.',
  },
  'Goberian': {
    group: 'Mixed Breed (Golden Retriever × Siberian Husky)', size: 'large',
    activityLevel: 5, walkMinsPerDay: 90, idealWalksPerDay: 2,
    weightRangeKg: [25, 40], caloriesPerKgBase: 60,
    coat: 'Dense double coat, golden or wolf-like',
    temperament: 'Friendly, energetic, loyal, intelligent',
    traits: ['Striking looks from both parents', 'Often has blue eyes', 'Loves to run', 'Very social'],
    healthNotes: 'Hip dysplasia from both sides. Eye conditions from Husky side.',
    feedingNotes: 'Very active — may need 1400-1600 kcal/day. Quality protein diet.',
    originalPurpose: 'Companion',
    fun: 'Often inherits the stunning blue eyes of the Husky with the golden coat of the Retriever.',
  },
  'Puggle': {
    group: 'Mixed Breed (Pug × Beagle)', size: 'small',
    activityLevel: 3, walkMinsPerDay: 45, idealWalksPerDay: 2,
    weightRangeKg: [7, 14], caloriesPerKgBase: 68,
    coat: 'Short, smooth, fawn or tan',
    temperament: 'Affectionate, playful, gentle, curious',
    traits: ['Less breathing problems than Pug', 'Loves to follow nose like Beagle', 'Sociable'],
    healthNotes: 'Some brachycephalic issues still possible. Epilepsy from Beagle side.',
    feedingNotes: 'Prone to obesity from both parents. Strict portions.',
    originalPurpose: 'Companion',
    fun: 'First popular Pug crossbreed and helped launch the "puggle" naming trend.',
  },
  'Cavachon': {
    group: 'Mixed Breed (Cavalier King Charles Spaniel × Bichon Frisé)', size: 'small',
    activityLevel: 2, walkMinsPerDay: 30, idealWalksPerDay: 2,
    weightRangeKg: [5, 9], caloriesPerKgBase: 75,
    coat: 'Soft, silky, wavy, white with patches',
    temperament: 'Sweet, gentle, playful, sociable',
    traits: ['Perfect lap dog', 'Great with elderly and children', 'Low-shedding', 'Loves cuddles'],
    healthNotes: 'Heart disease from Cavalier side. Skin allergies from Bichon side.',
    feedingNotes: 'Small breed twice daily. Quality food. Monitor weight.',
    originalPurpose: 'Companion',
    fun: 'Consistently ranked among the most gentle and easy-going crossbreeds.',
  },
  'Boxador': {
    group: 'Mixed Breed (Boxer × Labrador)', size: 'large',
    activityLevel: 4, walkMinsPerDay: 60, idealWalksPerDay: 2,
    weightRangeKg: [25, 40], caloriesPerKgBase: 60,
    coat: 'Short, dense, various colours',
    temperament: 'Playful, loyal, energetic, family-oriented',
    traits: ['Best of both parents', 'Excellent family dog', 'Loves to play', 'Some brachycephalic traits'],
    healthNotes: 'Heart conditions from both parents. Hip dysplasia. Bloat risk.',
    feedingNotes: 'Feed twice daily. Slow feeder bowl recommended. High-quality protein.',
    originalPurpose: 'Family companion',
    fun: 'Combines the playfulness of the Boxer with the loyalty of the Labrador.',
  },
  'Schnoodle': {
    group: 'Mixed Breed (Schnauzer × Poodle)', size: 'medium',
    activityLevel: 4, walkMinsPerDay: 60, idealWalksPerDay: 2,
    weightRangeKg: [6, 30], caloriesPerKgBase: 65,
    coat: 'Soft or wiry, low-shedding',
    temperament: 'Smart, loving, active, loyal',
    traits: ['Very intelligent', 'low-shedding', 'Versatile size'],
    healthNotes: 'Progressive retinal atrophy. Addison\'s disease from Poodle side.',
    feedingNotes: 'Varies hugely by size. Quality protein-based food.',
    originalPurpose: 'Companion',
    fun: 'The intelligence of the Schnauzer combined with Poodle smarts — incredibly trainable.',
  },
  'Yorkipoo': {
    group: 'Mixed Breed (Yorkshire Terrier × Poodle)', size: 'small',
    activityLevel: 3, walkMinsPerDay: 30, idealWalksPerDay: 2,
    weightRangeKg: [2, 6], caloriesPerKgBase: 85,
    coat: 'Silky or curly, low-shedding, golden or black',
    temperament: 'Lively, playful, gentle, confident',
    traits: ['Hypoallergenic tendencies', 'Big personality in tiny body', 'Apartment friendly'],
    healthNotes: 'Patellar luxation. Dental disease common.',
    feedingNotes: 'Tiny portions. Small-breed specific nutrition.',
    originalPurpose: 'Companion',
    fun: 'Tiny enough to fit in a handbag but with the confidence of a Great Dane.',
  },

  // ── RARE & UNUSUAL BREEDS ─────────────────────────────
  'Azawakh': {
    group: 'Hound (Rare)', size: 'large', activityLevel: 5,
    walkMinsPerDay: 90, idealWalksPerDay: 2,
    weightRangeKg: [15, 25], caloriesPerKgBase: 70,
    coat: 'Extremely short, fine, sand/fawn/brindle',
    temperament: 'Loyal, affectionate to family, aloof with strangers, fierce',
    traits: ['Sighthound from West Africa', 'Incredibly lean physique (ribs visible is normal)', 'Explosive speed', 'Bond deeply with one person'],
    healthNotes: 'Epilepsy relatively common. Cardiac issues. Sensitive to cold. Their lean physique is natural — do not assume they are underweight.',
    feedingNotes: 'Their lean appearance is breed-typical. Do not over-feed. High-quality protein diet.',
    originalPurpose: 'Hunting gazelle with the Tuareg people in the Sahara',
    fun: 'One of the rarest breeds in the world — fewer than 200 registered in the UK.',
  },
  'Bergamasco Shepherd': {
    group: 'Herding (Rare)', size: 'large', activityLevel: 3,
    walkMinsPerDay: 60, idealWalksPerDay: 2,
    weightRangeKg: [26, 38], caloriesPerKgBase: 52,
    coat: 'Unique felted "flocks" — three types of hair that naturally mat into flat mats',
    temperament: 'Patient, steady, sociable, intelligent',
    traits: ['Unique matted "flocked" coat', 'Ancient breed', 'Calm and patient'],
    healthNotes: 'Generally very hardy. Eye conditions in some lines.',
    feedingNotes: 'Quality protein. Twice daily. Surprisingly efficient metabolism.',
    originalPurpose: 'Herding and guarding flocks in the Italian Alps',
    fun: 'Their unique coat is not matted by neglect — the three types of hair naturally weave into flat mats called "flocks."',
  },
  'Xoloitzcuintli': {
    group: 'Primitive (Rare)', size: 'medium', activityLevel: 3,
    walkMinsPerDay: 45, idealWalksPerDay: 2,
    weightRangeKg: [4, 20], caloriesPerKgBase: 68,
    coat: 'Hairless (or coated variety), tough skin',
    temperament: 'Calm, alert, loyal, loyal, dignified',
    traits: ['Hairless — no shedding!', 'One of the world\'s oldest breeds', 'Low allergen', 'Warm to the touch'],
    healthNotes: 'Sunburn risk — apply sunscreen on walks. Dental issues common. Sensitive skin.',
    feedingNotes: 'Apply sunscreen before sunny walks! Quality diet with skin-supporting nutrients.',
    originalPurpose: 'Sacred dog of the Aztecs, believed to guide souls to the afterlife',
    fun: 'Also called "Xolo" (show-low). Aztecs believed owning one protected the house from evil spirits.',
  },
  'Otterhound': {
    group: 'Hound (Rare)', size: 'large', activityLevel: 4,
    walkMinsPerDay: 60, idealWalksPerDay: 2,
    weightRangeKg: [30, 52], caloriesPerKgBase: 54,
    coat: 'Rough, oily, water-resistant double coat',
    temperament: 'Boisterous, amiable, even-tempered, friendly',
    traits: ['Critically endangered — fewer than 600 worldwide', 'Loves water', 'Excellent nose', 'Loud voice'],
    healthNotes: 'Hip and elbow dysplasia. Thrombocytopenia (blood platelet condition).',
    feedingNotes: 'Large and active — quality protein diet. 2 meals per day.',
    originalPurpose: 'Hunting otters in rivers (now banned)',
    fun: 'One of the rarest breeds in the UK — there are fewer Otterhounds than Giant Pandas.',
  },
  'Norwegian Lundehund': {
    group: 'Non-Sporting (Rare)', size: 'small', activityLevel: 4,
    walkMinsPerDay: 45, idealWalksPerDay: 2,
    weightRangeKg: [5, 9], caloriesPerKgBase: 75,
    coat: 'Dense, rough, reddish-brown and white',
    temperament: 'Energetic, alert, loyal, protective',
    traits: ['Six toes on each foot!', 'Can close ears', 'Head bends backwards to touch spine', 'Extremely flexible'],
    healthNotes: 'Lundehund Syndrome (protein-losing intestinal disease) affects most of the breed. Very special diet needed.',
    feedingNotes: 'Many need special low-fat, highly digestible diets due to Lundehund Syndrome. Consult vet.',
    originalPurpose: 'Puffin hunting in Norwegian cliff faces',
    fun: 'Has 6 toes, can close its ears, and its head can bend completely backwards — adaptations for climbing cliff faces to steal puffins from nests.',
  },
  'Chinook': {
    group: 'Working (Rare)', size: 'large', activityLevel: 4,
    walkMinsPerDay: 60, idealWalksPerDay: 2,
    weightRangeKg: [25, 41], caloriesPerKgBase: 55,
    coat: 'Dense, tawny double coat',
    temperament: 'Patient, friendly, calm, devoted',
    traits: ['State dog of New Hampshire', 'Almost extinct in 1981 (only 11 left)', 'Versatile working dog'],
    healthNotes: 'Hip dysplasia and epilepsy.',
    feedingNotes: 'Quality large-breed food. 2 meals per day.',
    originalPurpose: 'Sled dog racing and freight hauling',
    fun: 'In 1981, there were only 11 Chinooks left in the world. Dedicated breeders saved the breed from extinction.',
  },
  'Mudi': {
    group: 'Herding (Rare)', size: 'medium', activityLevel: 5,
    walkMinsPerDay: 75, idealWalksPerDay: 2,
    weightRangeKg: [8, 13], caloriesPerKgBase: 72,
    coat: 'Wavy to curly, short on face, various colours',
    temperament: 'Energetic, versatile, brave, intelligent',
    traits: ['One of Hungary\'s finest herding dogs', 'Can herd sheep, hunt boar, and detect avalanche victims', 'Very rare outside Hungary'],
    healthNotes: 'Generally very healthy. Hip dysplasia in some lines.',
    feedingNotes: 'Active and high-energy — protein-rich diet.',
    originalPurpose: 'All-purpose Hungarian farm and herding dog',
    fun: 'Can herd sheep, hunt wild boar, find avalanche victims, and compete in agility — possibly the world\'s most versatile dog.',
  },
  'Lagotto Romagnolo': {
    group: 'Sporting (Rare)', size: 'medium', activityLevel: 4,
    walkMinsPerDay: 60, idealWalksPerDay: 2,
    weightRangeKg: [13, 16], caloriesPerKgBase: 68,
    coat: 'Thick, curly, woolly, water-resistant',
    temperament: 'Keen, affectionate, lively, undemanding',
    traits: ['World\'s foremost truffle hunter', 'Curly coat like a "teddy bear"', 'Excellent nose', 'Loves to dig'],
    healthNotes: 'Hip dysplasia and storage disease in some lines. Cerebellar ataxia in some lines.',
    feedingNotes: 'Moderate energy breed. Feed twice daily quality diet.',
    originalPurpose: 'Water retrieval and truffle hunting in Italy',
    fun: 'The only breed officially recognised for truffle hunting — worth their weight in gold (truffles sell for £3,000/kg!).',
  },
  'Cirneco dell\'Etna': {
    group: 'Hound (Rare)', size: 'medium', activityLevel: 5,
    walkMinsPerDay: 75, idealWalksPerDay: 2,
    weightRangeKg: [8, 12], caloriesPerKgBase: 72,
    coat: 'Short, fine, chestnut/tan',
    temperament: 'Friendly, independent, gentle, alert',
    traits: ['Ancient Sicilian breed (3,000 years old)', 'Can hunt without food or water for hours', 'Extremely athletic'],
    healthNotes: 'Sensitive to anaesthesia. Hypothyroidism in some.',
    feedingNotes: 'Lean, efficient metabolism. Don\'t overfeed. High-quality protein.',
    originalPurpose: 'Hunting rabbits on the slopes of Mount Etna',
    fun: 'Named after Mount Etna in Sicily — depictions appear on coins from 500 BC!',
  },
  'Sloughi': {
    group: 'Hound (Rare)', size: 'large', activityLevel: 5,
    walkMinsPerDay: 90, idealWalksPerDay: 2,
    weightRangeKg: [18, 27], caloriesPerKgBase: 62,
    coat: 'Short, fine, fawn/sandy',
    temperament: 'Dignified, sensitive, aloof with strangers, devoted',
    traits: ['North African sighthound', 'Sensitive and elegant', 'Extremely fast', 'One-family dog'],
    healthNotes: 'Sensitive to anaesthesia. Progressive retinal atrophy.',
    feedingNotes: 'Lean sighthound — high-quality protein to maintain muscle.',
    originalPurpose: 'Coursing gazelle and hare in North Africa',
    fun: 'Called the "Arabian Greyhound" — one of the oldest domesticated breeds.',
  },
  'Komondor': {
    group: 'Working (Rare)', size: 'large', activityLevel: 3,
    walkMinsPerDay: 60, idealWalksPerDay: 2,
    weightRangeKg: [36, 61], caloriesPerKgBase: 48,
    coat: 'Long, white, matted cords (dreadlock-like)',
    temperament: 'Steady, fearless, devoted, gentle with family',
    traits: ['Living mop appearance', 'Coat forms naturally matted cords', 'Powerful protector', 'Very rare'],
    healthNotes: 'Hip dysplasia. Bloat risk. Skin infections under cords if not dried properly.',
    feedingNotes: 'Large breed — 2 meals per day. Quality large-breed diet.',
    originalPurpose: 'Guardian of Hungarian livestock (looks like a sheep to hide among the flock)',
    fun: 'Their corded coat helps them blend in with sheep and sneak up on wolves!',
  },
  'Puli': {
    group: 'Herding (Rare)', size: 'medium', activityLevel: 4,
    walkMinsPerDay: 60, idealWalksPerDay: 2,
    weightRangeKg: [10, 15], caloriesPerKgBase: 66,
    coat: 'Long, corded dreadlock coat, black/white/grey',
    temperament: 'Energetic, smart, agile, loyal',
    traits: ['Dreadlock coat', 'Agile — can jump over sheep', 'Hungarian herding legend'],
    healthNotes: 'Hip dysplasia, eye conditions.',
    feedingNotes: 'Active breed — quality protein diet. Twice daily.',
    originalPurpose: 'Herding sheep in Hungary (leaps over their backs)',
    fun: 'Famous for their leaping — Pulik (plural) can jump over the backs of their sheep.',
  },
  'Canaan Dog': {
    group: 'Herding (Rare)', size: 'medium', activityLevel: 4,
    walkMinsPerDay: 60, idealWalksPerDay: 2,
    weightRangeKg: [16, 25], caloriesPerKgBase: 62,
    coat: 'Medium-length double coat, sand to red-brown',
    temperament: 'Alert, vigilant, territorial, devoted',
    traits: ['Ancient breed from Canaan region', 'Feral survival instincts', 'Highly alert', 'Independent'],
    healthNotes: 'Generally extremely hardy. Few genetic diseases due to natural selection.',
    feedingNotes: 'Efficient metabolism — don\'t overfeed. Quality balanced diet.',
    originalPurpose: 'Herding and guarding in ancient Canaan (Israel/Palestine region)',
    fun: 'Some Canaan Dogs still live semi-wild in the Negev Desert. They are the national dog of Israel.',
  },
  'Thai Ridgeback': {
    group: 'Primitive (Rare)', size: 'large', activityLevel: 4,
    walkMinsPerDay: 60, idealWalksPerDay: 2,
    weightRangeKg: [16, 34], caloriesPerKgBase: 60,
    coat: 'Short, smooth, with a ridge of reversed hair on back',
    temperament: 'Active, loyal, alert, independent',
    traits: ['Only 3 dog breeds in the world have a ridge', 'Ancient Thai breed', 'Rarely seen outside Southeast Asia'],
    healthNotes: 'Dermoid sinus (as with Ridgeback). Generally very healthy.',
    feedingNotes: 'Active breed. Quality protein-based diet.',
    originalPurpose: 'Hunting cobras and guarding carts in Thailand',
    fun: 'Used to hunt cobras in rural Thailand. One of only 3 dogs with a "ridge" — joining the Rhodesian Ridgeback.',
  },
  'Peruvian Inca Orchid': {
    group: 'Primitive (Rare)', size: 'medium', activityLevel: 4,
    walkMinsPerDay: 60, idealWalksPerDay: 2,
    weightRangeKg: [4, 25], caloriesPerKgBase: 65,
    coat: 'Hairless (or coated), various skin tones',
    temperament: 'Affectionate, alert, loyal, lively',
    traits: ['Hairless — no shedding', 'Warm skin', 'Sacred to the Inca', 'Various sizes'],
    healthNotes: 'Sunburn (apply sunscreen). Dental issues common in hairless dogs. Sensitive skin.',
    feedingNotes: 'Apply sunscreen before sunny walks. Skin-supporting diet.',
    originalPurpose: 'Sacred companion to the Inca Empire',
    fun: 'Machu Picchu has a colony of Peruvian Hairless Dogs that live at the site as living monuments.',
  },
  'Karelian Bear Dog': {
    group: 'Northern (Rare)', size: 'large', activityLevel: 5,
    walkMinsPerDay: 90, idealWalksPerDay: 2,
    weightRangeKg: [20, 32], caloriesPerKgBase: 65,
    coat: 'Dense, straight, black and white',
    temperament: 'Brave, independent, aggressive with other animals, loyal',
    traits: ['Used to hunt bears, moose and wolves', 'National treasure of Finland', 'Not suitable for first-time owners'],
    healthNotes: 'Generally very healthy. Hip dysplasia in some lines.',
    feedingNotes: 'Working dog energy needs. Protein-rich food. 2 meals per day.',
    originalPurpose: 'Hunting large game (bear, moose, wolf) in Finland',
    fun: 'National Parks in the USA and Canada use Karelian Bear Dogs to safely herd bears away from humans without harming them.',
  },
  'Stabyhoun': {
    group: 'Sporting (Rare)', size: 'medium', activityLevel: 4,
    walkMinsPerDay: 60, idealWalksPerDay: 2,
    weightRangeKg: [14, 20], caloriesPerKgBase: 64,
    coat: 'Long, black and white spotted',
    temperament: 'Gentle, patient, obedient, easy-going',
    traits: ['One of the rarest breeds outside Netherlands', 'Gentle and patient', 'All-purpose farm dog'],
    healthNotes: 'Epilepsy and hip dysplasia in some lines.',
    feedingNotes: 'Moderate energy — quality balanced diet.',
    originalPurpose: 'Hunting, herding, and guard dog in the Netherlands',
    fun: 'There are only about 7,000 Stabyhouns in the world — nearly all in the Netherlands.',
  },
  'Plott Hound': {
    group: 'Hound (Rare)', size: 'large', activityLevel: 4,
    walkMinsPerDay: 60, idealWalksPerDay: 2,
    weightRangeKg: [20, 27], caloriesPerKgBase: 60,
    coat: 'Short, glossy, brindle',
    temperament: 'Alert, bold, loyal, intelligent',
    traits: ['Only AKC breed not from England', 'Fearless bear hunter', 'State dog of North Carolina'],
    healthNotes: 'Hip dysplasia and bloat risk.',
    feedingNotes: 'High-energy hunting dog. Protein-rich food.',
    originalPurpose: 'Bear and boar hunting in the Appalachian Mountains',
    fun: 'The Plott Hound is the only AKC-recognised hound breed that does NOT have English origins — developed in America by German immigrant Johannes Georg Plott.',
  },
};

// ──────────────────────────────────────────────────────
// Helper: get breed data (case-insensitive fuzzy match)
// ──────────────────────────────────────────────────────
function getBreedData(breedName) {
  if (!breedName) return null;
  const norm = breedName.trim().toLowerCase();
  for (const [key, val] of Object.entries(BREED_DATABASE)) {
    if (key.toLowerCase() === norm) return { name: key, ...val };
  }
  // Partial match
  for (const [key, val] of Object.entries(BREED_DATABASE)) {
    if (key.toLowerCase().includes(norm) || norm.includes(key.toLowerCase().split(' ')[0].toLowerCase())) {
      return { name: key, ...val };
    }
  }
  return null;
}

function getAllBreedNames() {
  return Object.keys(BREED_DATABASE).sort();
}

// Activity level label
function activityLabel(level) {
  return ['','Low','Moderate','Active','High Energy','Very High Energy'][level] || '';
}

// Size label
function sizeBadge(size) {
  const map = { small:'🐶 Small', medium:'🐕 Medium', large:'🦮 Large', giant:'🐘 Giant' };
  return map[size] || size;
}

// ──────────────────────────────────────────────────────
// Feeding calculator
// weeklyWalkMins: total walk minutes in the last 7 days
// weightKg: dog's weight
// breed: breed name string
// Returns: { kcalPerDay, portionGrams, adjustment, note }
// ──────────────────────────────────────────────────────
function calculateFeeding(breedName, weightKg, weeklyWalkMins) {
  const breed = getBreedData(breedName);
  const baseKcalPerKg = breed ? breed.caloriesPerKgBase : 60;
  const targetWeeklyMins = breed ? breed.walkMinsPerDay * 7 : 420;

  let base = baseKcalPerKg * (weightKg || 10);
  let adjustment = 1.0;
  let note = '';
  let activityNote = '';

  if (weeklyWalkMins === null || weeklyWalkMins === undefined) {
    note = 'No walk data yet — using standard maintenance calories.';
    activityNote = 'Normal';
  } else {
    const ratio = weeklyWalkMins / Math.max(targetWeeklyMins, 1);
    if (ratio < 0.35) {
      adjustment = 0.88;
      note = '⬇️ Your dog has been quite inactive this week. Reduce food by ~12% to prevent weight gain.';
      activityNote = 'Low activity';
    } else if (ratio < 0.65) {
      adjustment = 0.94;
      note = '⬇️ Slightly below target exercise. Reduce food by ~6%.';
      activityNote = 'Below average';
    } else if (ratio <= 1.15) {
      adjustment = 1.0;
      note = '✅ Activity levels are on target. Serving normal portion.';
      activityNote = 'On target';
    } else if (ratio <= 1.5) {
      adjustment = 1.12;
      note = '⬆️ Great activity this week! Increase food by ~12% to support energy needs.';
      activityNote = 'Above average';
    } else {
      adjustment = 1.25;
      note = '⬆️ Very high activity this week! Increase food by ~25% to match energy expenditure.';
      activityNote = 'Very active';
    }
  }

  const kcalPerDay = Math.round(base * adjustment);
  // Rough estimate: typical dry dog food ~350 kcal/100g
  const portionGrams = Math.round(kcalPerDay / 3.5);

  return { kcalPerDay, portionGrams, adjustment, note, activityNote, targetWeeklyMins };
}
